# Generated by Django 5.2.13 on 2026-05-02 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ItemList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("gameID", models.CharField(max_length=20, null=True)),
                ("gameName", models.CharField(default="test", max_length=20)),
                ("itemName", models.CharField(max_length=20)),
                ("currentPrice", models.DecimalField(decimal_places=0, max_digits=10)),
                ("itemUrl", models.CharField(max_length=150)),
            ],
        ),
    ]
