# Generated by Django 5.0.12 on 2025-02-20 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ItemList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("index", models.IntegerField()),
                ("itemName", models.CharField(max_length=10)),
                ("currentPrice", models.DecimalField(decimal_places=0, max_digits=10)),
            ],
        ),
    ]
