# Generated by Django 5.0.12 on 2025-02-28 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webapp", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="itemlist",
            name="index",
        ),
        migrations.AddField(
            model_name="itemlist",
            name="gameID",
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="itemlist",
            name="gameName",
            field=models.CharField(default="test", max_length=20),
        ),
        migrations.AlterField(
            model_name="itemlist",
            name="itemName",
            field=models.CharField(max_length=20),
        ),
    ]
